We want to calculate and write the energies $\chi_{1,s}$ and statistical weights $g_{1,s}$ of hydrogen to a .txt tile. The energies and statistical weights are given as
$\begin{equation}
    g_{1,s} = 2s^2
\end{equation}
\begin{equation}
    \chi_{1,s} = 13.598(1-1/s^2)eV
\begin{equation}$

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
from astropy import constants
from astropy import units
from astropy.io import ascii

After importing the usual packages used for scientific programing, the energies and weights are defined as functions in python.

In [2]:
g   = lambda s: 2 * s ** 2
chi = lambda s: 13.598 * (1 - 1 / s ** 2) * units.eV

In [44]:
s = np.arange(1, 101, 1)
ascii.write([s, chi(s), g(s)], "H_energies_weights.dat",
            formats = {"s:": "%10.6f", "chi:": "%10.6f", "g:": "%10.6f"}, 
            names = ["s:", "chi:", "g:"])


In [45]:
print(np.loadtxt("H_energies_weights.dat", skiprows = 1))

[[1.0000000e+00 0.0000000e+00 2.0000000e+00]
 [2.0000000e+00 1.0198500e+01 8.0000000e+00]
 [3.0000000e+00 1.2087111e+01 1.8000000e+01]
 [4.0000000e+00 1.2748125e+01 3.2000000e+01]
 [5.0000000e+00 1.3054080e+01 5.0000000e+01]
 [6.0000000e+00 1.3220278e+01 7.2000000e+01]
 [7.0000000e+00 1.3320490e+01 9.8000000e+01]
 [8.0000000e+00 1.3385531e+01 1.2800000e+02]
 [9.0000000e+00 1.3430123e+01 1.6200000e+02]
 [1.0000000e+01 1.3462020e+01 2.0000000e+02]
 [1.1000000e+01 1.3485620e+01 2.4200000e+02]
 [1.2000000e+01 1.3503569e+01 2.8800000e+02]
 [1.3000000e+01 1.3517538e+01 3.3800000e+02]
 [1.4000000e+01 1.3528622e+01 3.9200000e+02]
 [1.5000000e+01 1.3537564e+01 4.5000000e+02]
 [1.6000000e+01 1.3544883e+01 5.1200000e+02]
 [1.7000000e+01 1.3550948e+01 5.7800000e+02]
 [1.8000000e+01 1.3556031e+01 6.4800000e+02]
 [1.9000000e+01 1.3560332e+01 7.2200000e+02]
 [2.0000000e+01 1.3564005e+01 8.0000000e+02]
 [2.1000000e+01 1.3567166e+01 8.8200000e+02]
 [2.2000000e+01 1.3569905e+01 9.6800000e+02]
 [2.300000